Requires on vhost creates dependency cycle
The vhost defined type from puppetlabs-apache already requires/notifies the
appropriate resources.

Error: Could not apply complete catalog: Found 1 dependency cycle:
(Exec[concat_25-puppetdb.example.com.conf] => File[25-puppetdb.example.com.conf] =>
File[25-puppetdb.example.com.conf symlink] =>
Apache::Vhost[puppetdb.example.com] =>
Class[Puppetexplorer::Apache] => Apache::Vhost[puppetdb.example.com] =>
File[25-puppetdb.example.com.conf symlink])